// Generates the Russian voice-over clips for every subtitle line using
// Microsoft Edge's neural voices (free, no account), into public/voice/,
// and writes the manifest src/voiceClips.ts. Incremental: existing clips
// are kept unless --force is given.
//
//   npm run voice                                 (ru-RU-SvetlanaNeural)
//   npm run voice -- ru-RU-DariyaNeural
//   npm run voice -- ru-RU-SvetlanaNeural --force
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { MsEdgeTTS, OUTPUT_FORMAT } from 'msedge-tts';
import { voiceKey } from '../src/voiceText';
import { allSpokenLines } from '../src/voiceLines';

const args = process.argv.slice(2).filter((a) => a !== '--force');
const force = process.argv.includes('--force');
const VOICE = args[0] ?? 'ru-RU-SvetlanaNeural';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(root, 'public', 'voice');
fs.mkdirSync(outDir, { recursive: true });

// ---- every line the game can say
const lines = new Set<string>(allSpokenLines());

// ---- generate
const tts = new MsEdgeTTS();
await tts.setMetadata(VOICE, OUTPUT_FORMAT.AUDIO_24KHZ_48KBITRATE_MONO_MP3);
let made = 0;
let bytes = 0;
const manifest: Record<string, string> = {};
for (const spoken of [...lines].sort()) {
  const key = voiceKey(spoken);
  const file = path.join(outDir, `${key}.mp3`);
  manifest[key] = spoken;
  if (!force && fs.existsSync(file)) continue;
  const { audioStream } = tts.toStream(spoken, { rate: '-8%' });
  const chunks: Buffer[] = [];
  for await (const chunk of audioStream) chunks.push(Buffer.from(chunk as Uint8Array));
  const buf = Buffer.concat(chunks);
  if (buf.length < 1000) throw new Error(`suspiciously small clip for: ${spoken}`);
  fs.writeFileSync(file, buf);
  made++;
  bytes += buf.length;
  console.log(`${key}  ${spoken}`);
}
tts.close();

// ---- drop clips whose line no longer exists
for (const f of fs.readdirSync(outDir)) {
  const key = f.replace(/\.mp3$/, '');
  if (f.endsWith('.mp3') && !manifest[key]) {
    fs.unlinkSync(path.join(outDir, f));
    console.log(`removed stale clip ${f}`);
  }
}

// ---- manifest
const entries = Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b));
const body = entries.map(([k, v]) => `  '${k}': ${JSON.stringify(v)},`).join('\n');
const header =
  '// GENERATED by `npm run voice` (tools/gen-voice.ts) — do not edit by hand.\n' +
  '// Maps voiceKey(spoken text) → the spoken text, for every clip in public/voice/.\n' +
  `// Voice: ${VOICE}\n`;
fs.writeFileSync(path.join(root, 'src', 'voiceClips.ts'), `${header}export const VOICE_CLIPS: Record<string, string> = {\n${body}\n};\n`);
console.log(`\n${lines.size} lines, ${made} new clips (${(bytes / 1024).toFixed(0)} KB), voice ${VOICE}`);
