// Where the voice actor's recordings live and how they reach the game. Shared
// by the dev-server studio plugin (vite.config.ts) and the CLI tools.
//
//   voice-takes/<key>.webm         the recording as it came from the microphone
//   public/voice-actor/<key>.webm  the same line after noise cleaning — what
//                                  the game plays (ships with the build)
//   src/voiceActor.ts              { key → clip file }  (ACTOR_CLIPS)
//   src/textOverrides.json         { key → reworded caption }
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

export const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export const ACTOR_DIR = path.join(ROOT, 'public', 'voice-actor');
export const RAW_DIR = path.join(ROOT, 'voice-takes');
export const MANIFEST = path.join(ROOT, 'src', 'voiceActor.ts');
export const OVERRIDES = path.join(ROOT, 'src', 'textOverrides.json');
export const KEY_RE = /^[0-9a-f]{8}$/;

export const EXT_BY_TYPE: Record<string, string> = {
  'audio/webm': 'webm',
  'audio/ogg': 'ogg',
  'audio/mp4': 'm4a',
  'audio/mpeg': 'mp3',
  'audio/wav': 'wav',
};
export const TYPE_BY_EXT: Record<string, string> = Object.fromEntries(Object.entries(EXT_BY_TYPE).map(([t, e]) => [e, t]));

export function writeIfChanged(file: string, src: string): void {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== src) fs.writeFileSync(file, src);
}

// { key → file name } for every <key>.<ext> in a folder.
export function clipsIn(dir: string): Record<string, string> {
  if (!fs.existsSync(dir)) return {};
  const out: Record<string, string> = {};
  for (const f of fs.readdirSync(dir).sort()) {
    const key = f.split('.')[0];
    if (KEY_RE.test(key)) out[key] = f;
  }
  return out;
}
export const actorClips = (): Record<string, string> => clipsIn(ACTOR_DIR);
export const rawClips = (): Record<string, string> => clipsIn(RAW_DIR);

export function removeClip(dir: string, key: string): void {
  if (!fs.existsSync(dir)) return;
  for (const f of fs.readdirSync(dir)) if (f.split('.')[0] === key) fs.unlinkSync(path.join(dir, f));
}

export function writeManifest(clips: Record<string, string> = actorClips()): void {
  const body = Object.entries(clips).map(([k, v]) => `  '${k}': ${JSON.stringify(v)},`).join('\n');
  const header =
    '// GENERATED by the recording studio (npm run studio) — do not edit by hand.\n' +
    '// Maps voiceKey(spoken text) → file name in public/voice-actor/ for every\n' +
    '// line recorded by a real person. These take priority over the TTS clips.\n';
  writeIfChanged(MANIFEST, `${header}export const ACTOR_CLIPS: Record<string, string> = {${body ? `\n${body}\n` : ''}};\n`);
}

// Recordings made before raw copies were kept: treat the game clip as the raw take.
export function importLegacyClips(): void {
  const raw = rawClips();
  for (const [key, file] of Object.entries(actorClips())) {
    if (raw[key]) continue;
    fs.mkdirSync(RAW_DIR, { recursive: true });
    fs.copyFileSync(path.join(ACTOR_DIR, file), path.join(RAW_DIR, file));
  }
}

// ---- reworded captions ------------------------------------------------------------
export function readOverrides(): Record<string, string> {
  try {
    const parsed = JSON.parse(fs.readFileSync(OVERRIDES, 'utf8')) as Record<string, unknown>;
    const out: Record<string, string> = {};
    for (const [k, v] of Object.entries(parsed)) if (KEY_RE.test(k) && typeof v === 'string' && v) out[k] = v;
    return out;
  } catch {
    return {};
  }
}

export function writeOverrides(texts: Record<string, string>): void {
  const sorted = Object.fromEntries(Object.entries(texts).sort(([a], [b]) => a.localeCompare(b)));
  writeIfChanged(OVERRIDES, `${JSON.stringify(sorted, null, 2)}\n`);
}
