// GENERATED by the recording studio (npm run studio) — do not edit by hand.
// Maps voiceKey(spoken text) → file name in public/voice-actor/ for every
// line recorded by a real person. These take priority over the TTS clips.
export const ACTOR_CLIPS: Record<string, string> = {
  '18e43cb1': "18e43cb1.webm",
  '1f4f8e84': "1f4f8e84.webm",
  '4225f210': "4225f210.webm",
  '7dd4b2d1': "7dd4b2d1.webm",
  '892c7a29': "892c7a29.webm",
  'a468fd41': "a468fd41.webm",
  'b0bd83fc': "b0bd83fc.webm",
  'e8d725b4': "e8d725b4.webm",
};
